"""GitHub pull request creation for generated TraceScribe docs."""

from __future__ import annotations

from dataclasses import dataclass

from github import Github
from github.GithubException import GithubException

from tracescribe.config import GitHubConfig
from tracescribe.jira_client import EpicData
from tracescribe.path_builder import slugify


@dataclass
class PRResult:
    url: str
    branch: str
    number: int


class GitHubError(Exception):
    """Raised when TraceScribe cannot create a documentation pull request."""


def _build_branch_name(epic: EpicData) -> str:
    summary_words = epic.summary.split()[:5]
    summary_slug = slugify("-".join(summary_words))
    if summary_slug:
        return f"tracescribe/{epic.key}-{summary_slug}"
    return f"tracescribe/{epic.key}"


def _build_pr_body(doc_path: str, epic: EpicData) -> str:
    components = ", ".join(epic.components) if epic.components else "None"
    fix_versions = ", ".join(epic.fix_versions) if epic.fix_versions else "None"
    return f"""## Auto-generated by TraceScribe

**Epic:** {epic.key}
**Assignee:** {epic.assignee}
**Component:** {components}
**Quarter:** {fix_versions}
**Status:** {epic.status}

---

This documentation was auto-generated from the Jira epic description using TraceScribe.
Please review the content carefully before merging.

**Doc path:** `{doc_path}`
"""


def create_doc_pr(
    doc_path: str,
    content: str,
    epic: EpicData,
    config: GitHubConfig,
) -> PRResult:
    """Commit the generated doc to a new branch and open a PR."""
    title = f"[TraceScribe] {epic.key}: {epic.summary}"
    branch_name = _build_branch_name(epic)

    try:
        client = Github(config.token, base_url=config.base_url)
        repo = client.get_repo(config.repo)
        base_branch = repo.get_branch(config.base_branch)

        try:
            repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=base_branch.commit.sha,
            )
        except GithubException as exc:
            if exc.status != 422 or "Reference already exists" not in str(exc.data):
                raise

        try:
            repo.create_file(
                path=doc_path,
                message=title,
                content=content,
                branch=branch_name,
            )
        except GithubException as exc:
            if exc.status == 422 and "already exists" in str(exc.data).lower():
                raise GitHubError(
                    f"Doc already exists at {doc_path} — delete it first or use a different epic key"
                ) from exc
            raise

        pull_request = repo.create_pull(
            title=title,
            body=_build_pr_body(doc_path, epic),
            head=branch_name,
            base=config.base_branch,
        )
    except GithubException as exc:
        if exc.status == 401:
            raise GitHubError("Invalid GitHub token — check your config") from exc
        if exc.status == 404:
            raise GitHubError(f"Repo {config.repo} not found or token lacks access") from exc
        raise GitHubError(str(exc)) from exc

    return PRResult(
        url=pull_request.html_url,
        branch=branch_name,
        number=pull_request.number,
    )
